name: glpi-docker-builder
# run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push: {}
  workflow_dispatch: {}

env:

  GLPI_DOCKER_REPO: "glpi-project/docker-images"
  GLPI_DOCKER_DIRECTORY: "./glpi-docker"
  GLPI_DOCKER_NIGHTLY_DIRECTORY: "glpi-nightly"
  GLPI_DOCKER_SOURCES_DIRECTORY: "sources"

  GLPI_APP_REPO: "glpi-project/glpi"
  GLPI_APP_TAG: "10.0.4"
  GLPI_APP_DIRECTORY: "./glpi"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      # - run: export

      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout glpi app
        uses: actions/checkout@v3
        with:
          repository: $GLPI_APP_REPO
          ref: $GLPI_APP_TAG
          path: $GLPI_APP_DIRECTORY

      - name: Checkout glpi-docker
        uses: actions/checkout@v3
        with:
          repository: $GLPI_DOCKER_REPO
          path: $GLPI_DOCKER_DIRECTORY

      - run: ls -lah

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Prepare source
      #   run: /bin/bash ./glpi-docker-builder.sh
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./glpi-docker/glpi/nightly
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest