name: glpi-docker-builder
# run-name: ${{ github.actor }} is learning GitHub Actions

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

env:

  GLPI_DOCKER_REPO: "glpi-project/docker-images"
  GLPI_DOCKER_DIRECTORY: "./glpi-docker"
  GLPI_DOCKER_NIGHTLY_DIRECTORY: "glpi-nightly"
  GLPI_DOCKER_SOURCES_DIRECTORY: "sources"

  GLPI_APP_REPO: "glpi-project/glpi"
  GLPI_APP_TAG: "10.0.10"
  GLPI_APP_DIRECTORY: "./glpi"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      # - run: export

      # - name: Checkout
      #   uses: actions/checkout@v3

      - name: Checkout glpi app
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GLPI_APP_REPO }}
          ref: ${{ env.GLPI_APP_TAG }}
          path: ${{ env.GLPI_APP_DIRECTORY }}

      - name: Checkout glpi-docker
        uses: actions/checkout@v3
        with:
          repository: glpi-project/docker-images
          path: ./glpi-docker

      - name: Prepare sources
        run: rm -rf ./glpi/.git; mv ./glpi ./glpi-docker/glpi-nightly/sources

      - run: ls -lah ./glpi-docker/glpi-nightly

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./glpi-docker/glpi-nightly
          file: ./glpi-docker/glpi-nightly/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/glpi:latest,${{ secrets.DOCKERHUB_USERNAME }}/glpi:${{ env.GLPI_APP_TAG }}
