name: glpi-docker-builder
# run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push: {}
  workflow_dispatch: {}

env:
  GLPI_DOCKER_REPO: "https://github.com/glpi-project/docker-images.git"  
  GLPI_DOCKER_DIRECTORY: "./glpi-docker"
  GLPI_DOCKER_NIGHTLY_DIRECTORY: "glpi-nightly"
  GLPI_DOCKER_SOURCES_DIRECTORY: "sources"
  GLPI_APP_REPO: "https://github.com/glpi-project/glpi.git"
  GLPI_APP_TAG: "10.0.4"
  GLPI_APP_DIRECTORY: "./glpi"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      # - run: export

      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare source
        run: /bin/bash ./glpi-docker-builder.sh
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./glpi-docker/glpi/nightly
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest